### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by robinmanuelthiel** [GitGuardian/homebrew-ggshield#1]
![image](https://user-images.githubusercontent.com/5874465/126030183-9c7e88dd-2ba6-4df1-a070-929676b193ab.png)

When visiting the link `https://ghcr.io/v2/homebrew/core/ggshield/manifests/1.7.2-1`, I see the following response:

```json
{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "authentication required"
    }
  ]
}
```

**Comment by robinmanuelthiel** [comment]
Workaround: Download the Release from the GitHub Releases and run

```bash
brew install -f ggshield-1.7.2.catalina.bottle.1.tar.gz
```

**Comment by Jguer** [comment]
Hey @robinmanuelthiel , sorry this issue slipped unnoticed. Have you been able to reproduce it with the latest version?

**Comment by robinmanuelthiel** [comment]
Looks like it works now with the current version. Thanks!
